dist: trusty
sudo: required

services:
  - docker

notifications:
  email: false

jobs:
  include:

    - stage: Build Apps
      script: >
        cd deploy/ &&
        npm install &&
        node build.js

    - stage: Deploy
      script: >
        cd deploy/ &&
        npm install &&
        echo DEPLOYING...
        # node deploy.js


stages:
  - Build Apps
  - name: Deploy
    if: branch = master

