dist: trusty
sudo: required

services:
  - docker

notifications:
  email: false

jobs:
  include:

    - stage: Build Apps
      script: >
        cd deploy/ &&
        npm install &&
        node build.js

stages:
  - Build Apps
  - name: Deploy
    if: branch = master

