dist: trusty
sudo: required
language: node_js
node_js:
  - "node"
branches:
  except:
  - gh-pages
notifications:
  email: false
services:
  - docker

env:
  - HEROKU_DOCKER_USERNAME
  - HEROKU_AUTH_TOKEN

install:
  - docker pull microsoft/dotnet:2.1-sdk
  - cd deploy/ && npm install && cd ..

script: >
  node deploy/build.js &&
  node deploy/deploy-heroku.js

deploy:
  provider: script
  script: node deploy/deploy-heroku.js
