dist: trusty
sudo: required

services:
  - docker

jobs:
  include:

    - stage: Restore dependencies
      script: cd deploy/ && npm install

    - stage: Build Apps
      script: >
        cd deploy/ &&
        npm install &&
        node deploy/build.js
    
    #   script: ./test 2

    # - stage: Deploy
    #   script: ./deploy

notifications:
  email: false