dist: trusty
sudo: required
branches:
  except:
  - gh-pages
notifications:
  email: false

services:
  - docker
install:
  - docker pull microsoft/dotnet:2.1-sdk
  - cd deploy/ && npm install && cd ..
script: >
  node deploy/build.js &&
  node deploy/deploy.js
