version: 2

jobs:

  futbol:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      # /deploy/
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "deploy/package.json" }}
      - run:
          name: Restore npm dependencies for deployment scripts
          command: npm install
          working_directory: deploy/
      - save_cache:
          paths:
            - deploy/node_modules/
          key: v1-dependencies-{{ checksum "deploy/package.json" }}
      # src/Client App/
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "src/Client App/package.json" }}
      - run:
          name: Restore npm dependencies for client app
          command: npm install
          working_directory: src/Client App/
      - save_cache:
          paths:
            - src/Client App/node_modules/
          key: v1-dependencies-{{ checksum "src/Client App/package.json" }}
      # src/
      - run:
          name: Build app
          command: npm run build
          working_directory: deploy/
      # dist/
      - deploy:
          name: Deploy app
          command: npm run deploy
          working_directory: deploy/
    
workflows:
  version: 2

  Build:
    jobs:
      - futbol
