version: 2

jobs:

  restore_deploy_scripts:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "deploy/package.json" }}
      - run:
          name: Restore npm dependencies for deployment scripts
          command: npm install
          working_directory: deploy/
      - save_cache:
          paths:
            - deploy/node_modules/
          key: v1-dependencies-{{ checksum "deploy/package.json" }}

  build_client_app:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "src/Client App/package.json" }}
      - run:
          name: Restore npm dependencies for client app
          command: npm install
          working_directory: src/Client App/
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "src/Client App/package.json" }}
      - run:
          name: Build client app
          command: npm run build
          working_directory: deploy/
      - deploy:
          name: Deploy app
          command: npm run deploy
          working_directory: deploy/

  deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - deploy:
          name: Deploy app
          command: npm run deploy
          working_directory: deploy/

workflows:
  version: 2

  Build:
    jobs:
      - restore_deploy_scripts
      - build_client_app
      - deploy
