version: '2'

services:

  web_app:
    container_name: futbol_web-app
    build:
      context: ../dist/
      dockerfile: ../deploy/web_api.Dockerfile
    ports:
      - '5000:80'
    networks:
      - futbol


networks:
  futbol:
    driver: bridge
