version: '2'

services:

  web_app:
    container_name: futbol_web-app
    build:
      context: ../dist/
    ports:
      - '5000:80'
    restart: on-failure
    links: 
      - postgres
    networks:
      - futbol

  postgres:
    container_name: futbol_postgres
    image: postgres:10
    expose:
      - 5432
    volumes:
      - '/var/futbol/postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=futbol
      - POSTGRES_USER=futbol
      - POSTGRES_PASSWORD=password
    networks:
      - futbol


networks:
  futbol:
    driver: bridge
